- pom.xml
* Built project as the release profile and saw RPM was considered an artifact in the output (i.e. the sha is generated for it, etc.)
> Making the RPM an artifact in the pom

- pom.xml
- src/assembly/artifacts.xml
This automates the collection of files that should be archived, published, etc. for a release.  I can now configure my Jenkins job to pull what it needs out of the new folder.
1. On a Fedora machine, ran:
```
mvn clean verify -P release
```
2. The Maven output contained the following near the end:
```
[INFO] --- maven-assembly-plugin:2.6:single (default) @ git-credential-manager ---
[INFO] Reading assembly descriptor: src/assembly/artifacts.xml
[INFO] Copying files to /home/oli/oss/gcm4ml/target/git-credential-manager-1.2.1-SNAPSHOT-artifacts
```
3.  I then listed the contents of the `target/git-credential-manager-1.2.1-SNAPSHOT-artifacts/` folder:
```
target/git-credential-manager-1.2.1-SNAPSHOT-artifacts/:
total 348
-rw-rw-r--. 1 oli oli   2258 Nov 19 23:48 Contributing.md
-rw-rw-r--. 1 …
```
> Collect release-worthy artifacts in a folder

- Install.md
- templates/Install.md
On my Fedora 22 machine:
1. Downloaded the `RPM-GPG-KEY-olivida.txt` file.
2. Imported it:
```
sudo rpm --import ~/Downloads/RPM-GPG-KEY-olivida.txt
```
3. Verified the key was imported:
```
rpm -qa gpg-pubkey* --qf '%{name} %{version} %{release} %{summary}\n'
```
...which produced the following output:
```
gpg-pubkey ba34dbc2 5605a22c gpg(Oli Dagenais (Microsoft) <olivida@microsoft.com>)
gpg-pubkey 8e1431d5 53bcbac7 gpg(Fedora (22) <fedora@fedoraproject.org>)
```
...and our key ID (**ba34dbc2**) is indeed there.
4. Ran a *release* build to force construction of the RPM:
```
mvn clean verify -P release -Dgpg.keyname='Oli Dagenais (Microsoft) <olivida@microsoft.com>'
```
5. Verified the signature of the generated RPM:
```
rpm --checksig --verbose …
```
> Fix RPM PGP key filename

- pom.xml
- templates/control
This addition creates a Debian package that can be installed on Debian platforms (i.e. Ubuntu). This will only occur when built as a release. A control file is needed for creation so that is added as a template that gets dynamically populated with the latest project info. 
* Tested building the project not as release and no deb file was created (on Fedora machine)
* Tested building the project as a release and a deb file was created (on Fedora machine)
* Moved the deb file to an Ubuntu machine and ran: `sudo dpkg -i <package>`
* Was able to call: `git-credential-manager install/uninstall`
* Tried to install the deb package without the proper git/java versions and it failed
> Adding .deb package creation

- src/main/java/com/microsoft/alm/authentication/BaseVsoAuthentication.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/InsecureStore.java
- src/test/java/com/microsoft/alm/authentication/TokenTest.java
- src/test/java/com/microsoft/alm/gitcredentialmanager/InsecureStoreTest.java
This PR removes references from the `authentication` package to the `gitcredentialmanager` package, making it easier to extract the `authentication` and `helpers` packages into a re-usable library.
It turns out the only uses going the "wrong way" were of the `InsecureStore` and they really were only using it as an in-memory store, something that the `SecretCache` already provides.
> Ensure clean separation between re-usable code and GCM app

- src/main/java/com/microsoft/alm/authentication/Credential.java
- src/main/java/com/microsoft/alm/authentication/Token.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/InsecureStore.java
- src/main/java/com/microsoft/alm/helpers/XmlHelper.java
- src/test/java/com/microsoft/alm/authentication/CredentialTest.java
- src/test/java/com/microsoft/alm/authentication/TokenTest.java
- src/test/java/com/microsoft/alm/helpers/StringHelperTest.java
`Credential` and `Token` now take more responsibility for serializing themselves to/from XML, which also made it easier to add relevant and concise unit tests.
> Refactor XML serialization

- src/main/java/com/microsoft/alm/authentication/KeychainSecurityCliStore.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/IComponentFactory.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/InsecureStore.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/OperationArguments.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
- src/test/groovy/com/microsoft/alm/authentication/KeychainSecurityCliStoreTest.groovy
- src/test/java/com/microsoft/alm/gitcredentialmanager/InsecureStoreTest.java
During testing, I noticed a few small improvements that could be made, so I included them as part of this pull request:
1. The `add-generic-password` command has an _update_ mode (`-U`) that avoids having to delete-then-add. (b7b1d4a)
2. Asking for a token or credential that does not exist will now return `null`. ( 41dd00b)
3. If the `insecureStore.xml` file exists, its entries will be imported and the file renamed to add a `.old` suffix. (6bf68ba)
4. Added a check to see if the keychain is available (it isn't through a remote shell, for example, unless it's been unlocked). If the keychain is not available, there's a configurable [opt-in] fallback to the `InsecureStore`, otherwise a `SecurityException` is thrown to fail as early as possible. (12c0766)
Manual testing
-------------- …
> Improve KeychainSecurityCliStore and then wire it up on Mac OS X

- src/main/java/com/microsoft/alm/authentication/KeychainSecurityCliStore.java
- src/main/java/com/microsoft/alm/helpers/StringHelper.java
- src/test/groovy/com/microsoft/alm/authentication/FifoProcess.groovy
- src/test/groovy/com/microsoft/alm/authentication/KeychainSecurityCliStoreTest.groovy
- src/test/java/com/microsoft/alm/helpers/StringHelperTest.java
This avoids having the password be a command-line argument, which could be seen in the list of running processes, etc.  Inspired by jaraco/keyring#165
Manual testing
--------------
Ran the ignored tests on the Mac Mini to verify the functionality still worked as expected.
> Use security in interactive mode for adding

- pom.xml
There were a couple of warnings during a Maven build that I took care of; see the individual commits for details.
Manual testing
--------------
Set my `JAVA_HOME` to JDK `1.6.0_20` on Windows and ran `mvn clean verify`.  There are no longer any warnings.
Mission accomplished!
> Fix Maven build-time warnings

- pom.xml
- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
- src/test/java/com/microsoft/alm/gitcredentialmanager/ProgramTest.java
- templates/Install.md
After upgrading oauth2-useragent to version 0.7.1, what was missing was setting the `java.net.useSystemProxies` system property when installing the GCM.
The installation documentation was likewise updated.  See the new [How to configure the proxy server](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/blob/support_proxy_servers/templates/Install.md#how-to-configure-the-proxy-server) section.
The manual testing was already done as part of microsoft/oauth2-useragent#17.
> Add support for proxy servers

- templates/Install.md
- templates/git-credential-manager.rb
As a follow-on to Microsoft/oauth2-useragent#19, update documentation and Homebrew formula to identify Java 8 when running on Mac OS X 10.11 (El Capitan) or greater.
Manual testing
==============
1. On a Mac running OS X 10.10.5 (Yosemite):
1. [Install Homebrew](http://brew.sh/).
2. Temporarily inject the changes to `Library/Formula/git-credential-manager.rb` in the Git repo that's cloned as part of installing Homebrew. 
3. Temporarily uninstall Java.
4. Attempt to install the `git-credential-manager` formula:
```
$ brew install git-credential-manager
git-credential-manager: Java 1.7+ is required to install this formula.
You can install with Homebrew Cask:
brew install Caskroom/cask/java
You can download from:
http://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An …
```
> Remove support for Java 7 on Mac OS X 10.11 and up

- src/main/java/com/microsoft/alm/authentication/AzureAuthority.java
- src/main/java/com/microsoft/alm/authentication/BaseVsoAuthentication.java
- src/main/java/com/microsoft/alm/authentication/Token.java
- src/main/java/com/microsoft/alm/authentication/VsoAzureAuthority.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/InsecureStore.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
A number of `catch` blocks were simply tracing or silently swallowing errors.  I reviewed and decided to re-throw in many of the cases, because it would allow an error condition to fail the program faster and with a more obvious cause.
On a Fedora 22 VM:
1. Disable direct access to the internet such that a proxy server must be used. 
2. Configure the proxy server by modifying the `credential.helper` value in `.gitconfig`:
1. Remove `-Djava.net.useSystemProxies=true`
2. Add `-Dhttps.proxyHost=192.168.0.117`
3. Add `-Dhttps.proxyPort=8123`
3. Rename `~/git-credential-manager/insecureStore.xml` to  `~/git-credential-manager/insecureStore.xml.old`
4. Attempt a `git fetch` in a clone of a Git repository hosted in VSTS.
1. Close the browser window that pops up.
2. The GCM4ML terminates (the …
> Fail faster and more explicitly

- pom.xml
- src/main/java/com/microsoft/alm/authentication/DeviceFlow.java
- src/main/java/com/microsoft/alm/authentication/DeviceFlowImpl.java
- src/main/java/com/microsoft/alm/authentication/DeviceFlowResponse.java
- src/main/java/com/microsoft/alm/authentication/OAuthParameter.java
- src/main/java/com/microsoft/alm/authentication/TokenPair.java
- src/main/java/com/microsoft/alm/helpers/HttpClient.java
- src/test/groovy/com/microsoft/alm/authentication/DeviceFlowImplTest.groovy
- src/test/groovy/com/microsoft/alm/authentication/DeviceFlowResponseTest.groovy
- src/test/java/com/microsoft/alm/authentication/LoggingFiltersSourceAdapter.java
These changes implement the **OAuth 2.0 Device Flow** according to my interpretation of the `draft-ietf-oauth-device-flow-01` specification.
> Initial Device Flow implementation

- src/main/java/com/microsoft/alm/authentication/AzureDeviceFlow.java
- src/main/java/com/microsoft/alm/authentication/AzureDeviceFlowResponse.java
- src/main/java/com/microsoft/alm/helpers/PropertyBag.java
- src/main/java/com/microsoft/alm/helpers/SimpleJson.java
- src/test/groovy/com/microsoft/alm/authentication/AzureDeviceFlowResponseTest.groovy
- src/test/groovy/com/microsoft/alm/authentication/AzureDeviceFlowTest.groovy
- src/test/groovy/com/microsoft/alm/helpers/PropertyBagTest.groovy
- src/test/groovy/com/microsoft/alm/helpers/SimpleJsonTest.groovy
There are a few differences from the OAuth 2.0 Device Flow specification draft 01 which this pull request bridges.
> Extend Device Flow to support Azure Active Directory

- src/main/java/com/microsoft/alm/authentication/AzureAuthority.java
- src/main/java/com/microsoft/alm/authentication/IAzureAuthority.java
- src/main/java/com/microsoft/alm/authentication/IVsoAadAuthentication.java
- src/main/java/com/microsoft/alm/authentication/IVsoMsaAuthentication.java
- src/main/java/com/microsoft/alm/authentication/VsoAadAuthentication.java
- src/main/java/com/microsoft/alm/authentication/VsoMsaAuthentication.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
- src/main/java/com/microsoft/alm/helpers/Trace.java
- src/test/java/com/microsoft/alm/authentication/AzureAuthorityTest.java
OAuth 2.0 Device Flow is now wired up and will be attempted as a last resort.
Manual testing
--------------
1. Add a Git remote to a clone of this repo pointing to a VSTS account that uses **Microsoft Accounts (MSA)**.  Let's call the remote `msarepo`.
2. Run `git push msarepo`.
3. When the JavaFX browser opens, immediately close the window.  This used to completely abort the GCM4ML; now we get something like this:
```
------------------------------------
OAuth 2.0 Device Flow authentication
------------------------------------
To complete the authentication process, please open a web browser and visit the following URI:
https://aka.ms/devicelogin
When prompted, enter the following code:
E3P3CAVVR
Once authenticated and authorized, execution will continue.
```
4. Follow the instructions …
> Wire up the new Device Flow feature

- src/test/groovy/com/microsoft/alm/authentication/DeviceFlowImplTest.groovy
- src/test/java/com/microsoft/alm/authentication/AzureAuthorityTest.java
- src/test/java/com/microsoft/alm/authentication/LoggingFiltersSourceAdapter.java
- src/test/java/com/microsoft/alm/helpers/NullUserAgent.java
> Minor unit test improvements

- pom.xml
- src/main/java/com/microsoft/alm/authentication/AzureAuthority.java
Manual Testing
--------------
These steps were performed on my Windows 10 workstation:
1. Temporarily disable the insecure store file to force authentication.  I did that by appending `.old` to `%LOCALAPPDATA%/git-credential-manager/insecureStore.xml`.
1. Create a file called input.txt containing the following:
```
protocol=https
host=mseng.visualstudio.com
```
1. Launch the GCM4ML in `get` mode, with stdin coming from `input.txt` and using a JRE that doesn't support JavaFX, such as Java 6.  This is what my command-line looked like:
```
/cygdrive/e/Software/Java/jdk1.6.0_20/bin/java -Ddebug=true -jar target/git-credential-manager-1.7.2-SNAPSHOT.jar get < input.txt
```
1. Before the changes from this pull request, we would have gotten the following _debug_ output:
``` …
```
> Reduce JavaFX failure output

- src/main/java/com/microsoft/alm/gitcredentialmanager/OperationArguments.java
- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
Also expand to any version of Git that makes `git-credential-osxkeychain` available, not just "Apple Git".  This covers the [Git OSX Installer](https://git-scm.com/download/mac) which has a more "traditional" version string, yet behaves the same with respect to hardcoding the osxkeychain credential helper first.
Manual testing
--------------
For each of the following distributions of Git:
1. Apple
2. Homebrew
3. OSX Installer
...performed a `git fetch` against a _Visual Studio Team Services_ Git repository and kept a close eye on the Keychain application.  For **Apple** and **OSX Installer**, an entry would briefly appear in the Keychain before being deleted by the GCM4ML.  In the **Homebrew** case, no entry appeared.  In all cases, the fetch succeeded.
Mission accomplished!
> Make hardcoded credential-osxkeychain workaround opt-out instead of opt-in

- src/main/java/com/microsoft/alm/authentication/AzureAuthority.java
- src/main/java/com/microsoft/alm/authentication/AzureDeviceFlow.java
- src/main/java/com/microsoft/alm/authentication/BaseVsoAuthentication.java
- src/main/java/com/microsoft/alm/authentication/IAzureAuthority.java
- src/main/java/com/microsoft/alm/authentication/VsoAadAuthentication.java
- src/main/java/com/microsoft/alm/authentication/VsoMsaAuthentication.java
- src/test/java/com/microsoft/alm/authentication/AzureAuthorityTest.java
Manual testing
--------------
1. Deleted the credentials associated with a _Visual Studio Team Services_ account.
2. Performed a `git fetch`.
3. The JavaFX-based web browser appeared (notice how it now says "Visual Studio Team Services"):
4. I completed the sign-in with 2-factor authentication.
5. The `fetch` completed.
6. I deleted the credentials again.
7. Performed a `git fetch` again.
8. The JavaFX-based web browser again appeared.
9. This time I closed the window.  The GCM4ML fell back to _Device Login_ mode and asked me to go to https://aka.ms/devicelogin and enter a user code.
10. I opened a browser and entered the user code (notice how it now says "Visual Studio Team Services"):
11. I completed the sign in.
12. The `fetch` completed.
Mission accomplished!
> Update the Azure Active Directory client ID

- src/main/java/com/microsoft/alm/authentication/VsoAzureAuthority.java
- src/test/groovy/com/microsoft/alm/authentication/VsoAzureAuthorityTest.groovy
Based on commit [70af3d ](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/pull/298/commits/70af3d7d7fa60b74c32fa765194ab8b942a46343)from Git-Credential_manager-for-Windows
Manual test:
1. Compile and install gcm4ml locally
2. Enable debug from .gitconfig
3. Remove cached credentials (on Mac, it's saved in keychain.)
4. Clone a repo hosted by VSTS and observe:
```
VsoAzureAuthority::populateTokenTargetId
VsoAzureAuthority::createConnectionDataRequest
validating token
target identity is add8a40a-597c-43ff-93fa-e0153bc896ab
parsed identity service url: https://app.vssps.visualstudio.com/Aadd8a40a-597c-43ff-93fa-e0153bc896ab/
creating access token scoped to 'vso.code_write' for 'add8a40a-597c-43ff-93fa-e0153bc896ab'
personal access token acquisition succeeded. …
```
> Support NEW VSTS Identity Service Requirement

- src/main/java/com/microsoft/alm/gitcredentialmanager/Program.java
With current implementation, the credentials will be stored in ~/.VSTeamServicesAuthPlugin/insecureStore.xml.
> Make the option to bypass secure storage more discoverable

- .travis.yml
- pom.xml
There was a change made to the oauth2-useragent dependency to fix an
issue with parsing newer versions of Java. This change updates to that
newer version to include the fix.
Additionally, it appears javax.xml.bind is no longer included with Java
9. This has been included as a maven dependency to resolve class def
errors once the oauth2-useragent error was resolved.
> Support Java 9+

- pom.xml
@whoisj @yacaovsnc @leantk @madhurig @kaylangan @jrbriggs  This preps for release 2.0.4 of GCM4ML so that people have some way of getting it with Java 9/Java 10 support.
> [maven-release-plugin] Prepare for release 2.0.4

- templates/git-credential-manager
The shell script to run the credential manager makes the assumption that JAVA_HOME is set. This is a crude attempt at just falling back to what's in the user's PATH if there's no JAVA_HOME set.
> Fallback when JAVA_HOME is not set
